from __future__ import annotations

from math import pi


# Legacy semantic accents remain for cp-diagram/v1 and v2 compatibility.
PALETTE = {
    "background": "#ffffff",
    "default": "#000000",
    "red": "#c43d3d",
    "blue": "#2f67b2",
    "green": "#2f7d4a",
}

STROKE_WIDTH = 2.0
ANNOTATION_STROKE_WIDTH = STROKE_WIDTH * 1.25
ROUGHNESS = 0.0
PADDING = 32
FONT_FAMILY = (
    "Comic Neue, AR PL KaitiM GB, Noto Sans CJK SC, Microsoft YaHei, sans-serif"
)
VALUE_FONT_SIZE = 20
ANNOTATION_LABEL_FONT_SIZE = 16
INDEX_FONT_SIZE = 12
ARRAY_LABEL_FONT_SIZE = INDEX_FONT_SIZE
INDEX_GAP = INDEX_FONT_SIZE * 0.4
CELL_HEIGHT = VALUE_FONT_SIZE * 2.2
MIN_CELL_WIDTH = VALUE_FONT_SIZE * 2.5
CELL_HORIZONTAL_PADDING = VALUE_FONT_SIZE * 0.6
ANNOTATION_STEP = ANNOTATION_LABEL_FONT_SIZE * 2.5
ANNOTATION_CLEARANCE = ANNOTATION_LABEL_FONT_SIZE * 1.7
INDEX_HEIGHT = INDEX_GAP + INDEX_FONT_SIZE + 4
LABEL_GAP = VALUE_FONT_SIZE * 0.9
INLINE_LABEL_PADDING = ANNOTATION_LABEL_FONT_SIZE * 0.5
MIN_RANGE_ARROW_LENGTH = ANNOTATION_LABEL_FONT_SIZE * 2.0
MULTI_ROW_GAP = VALUE_FONT_SIZE * 1.25
NODE_PRIMARY_FONT_SIZE = VALUE_FONT_SIZE
NODE_AUX_FONT_SIZE = INDEX_FONT_SIZE
NODE_FIELD_FONT_SIZE = ANNOTATION_LABEL_FONT_SIZE
NODE_LINE_GAP = 5
NODE_HORIZONTAL_PADDING = CELL_HORIZONTAL_PADDING
NODE_VERTICAL_PADDING = VALUE_FONT_SIZE * 0.45
MIN_NODE_DIAMETER = MIN_CELL_WIDTH
MIN_SQUARE_SIZE = MIN_CELL_WIDTH
MIN_RECTANGLE_WIDTH = MIN_CELL_WIDTH
MIN_RECTANGLE_HEIGHT = CELL_HEIGHT
NODE_INDEX_HEIGHT = INDEX_GAP + INDEX_FONT_SIZE + 4
EDGE_LABEL_FONT_SIZE = VALUE_FONT_SIZE
EDGE_LABEL_GAP = EDGE_LABEL_FONT_SIZE * 0.7
GRAPH_EDGE_LENGTH = 132
GRAPH_LAYOUT_SEED = 20260811
ANGULAR_FORCE_STRENGTH = 0.22
INDEX_CLEARANCE_FORCE_STRENGTH = 0.20
INDEX_CLEARANCE_ANGLE = pi / 5
TREE_HORIZONTAL_GAP = 34
TREE_VERTICAL_GAP = 54
SELF_LOOP_MARGIN = MIN_NODE_DIAMETER * 1.4
DASH_PATTERN = [7.0, 5.0]
FENWICK_SOURCE_GAP = 18
PROJECTION_VERTICAL_GAP = TREE_VERTICAL_GAP
PROJECTION_CELL_GAP_RATIO = 0.25
